apiVersion: v1
kind: Service
metadata:
  name: mavryk-node-rpc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8732
      name: rpc
  {{- with .Values.services.mavryk_node_rpc.selector | default (dict "appType" "mavkit-node") }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  type: NodePort
---
{{- range $key, $val := .Values.nodes }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  labels:
    appType: mavkit-node
spec:
  ports:
    - port: 8732
      name: rpc
    - port: 9732
      name: p2p
    - port: 9932
      name: metrics
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    node_class: {{ $key }}
---
{{- end }}
{{- if (include "mavryk.shouldDeployMvktIndexer" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mvkt_indexer_statefulset.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 5000
  selector:
    app: {{ .Values.mvkt_indexer_statefulset.name }}
  type: NodePort
{{- end }}
