---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.name }}-maven-finance-oracle'
  labels:
    app: '{{ .Values.name }}-maven-finance-oracle'
spec:
  clusterIP: None
  ports:
    - name: p2p
      port: 23456
      protocol: TCP
      targetPort: p2p
  selector:
    app: '{{ .Values.name }}-maven-finance-oracle'
  type: ClusterIP
