{{- if .Values.pgBouncer.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "indexer.configFile" . }}
  namespace: {{ $.Release.Namespace }}
data:
  pgbouncer.ini: |-
{{ include "pgbouncer.ini" . | indent 4 }}
{{- end }}