{{- if and .Values.hasura.enabled .Values.hasura.ingress.enabled}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "indexer.fullname" . }}
{{- with .Values.hasura.ingress.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
{{- end }}
  annotations:
{{- with .Values.hasura.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.hasura.ingress.className }}
  {{- if .Values.hasura.ingress.tls }}
  tls:
    {{- range .Values.hasura.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.hasura.ingress.host }}
      http:
        paths:
          - path: /
            pathType: {{ .Values.hasura.ingress.pathType }}
            backend:
              service:
                name: {{ include "indexer.fullname" . }}
                port:
                  number: 8080
{{- end }}
