{{- if .Values.pgBouncer.userlist }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "indexer.userlistFile" . }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
{{- if .Values.pgBouncer.userlist }}
  userlist.txt: |-
{{ include "userlist.txt" . | b64enc | indent 4 }}
{{- end }}
{{- end }}
