---
apiVersion: v1
kind: Service
metadata:
  name: mavryk-indexer-db
  labels:
    app: mavryk-indexer
spec:
  ports:
    - name: db
      port: 5432
      protocol: TCP
      targetPort: db
  selector:
    app: mavryk-indexer
  type: ClusterIP
