---
apiVersion: v1
kind: Service
metadata:
  name: mavryk-indexer-db
  labels:
    app: mavryk-indexer
spec:
  ports:
    - name: db
      port: 5432
      protocol: TCP
      targetPort: db
{{- if .Values.dipdupIndexer.metrics.enabled }}
    - name: metrics
      port: {{ .Values.dipdupIndexer.metrics.port }}
      protocol: TCP
      targetPort: metrics
{{- end }}
  selector:
    app: mavryk-indexer
  type: ClusterIP
