{{- if .Values.enableUI }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: faucet-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
{{- $_ := set .Values.config.application "disableChallenges" .Values.disableChallenges }}
{{- $_ := set .Values.config.application "minMav" .Values.minMav }}
{{- $_ := set .Values.config.application "maxMav" .Values.maxMav }}
{{ .Values.config | mustToPrettyJson | indent 4 }}
---
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: faucet-backend-config
  namespace: {{ .Release.Namespace }}
data:
  AUTHORIZED_HOST: "{{ .Values.authorizedHost }}"
  DISABLE_CHALLENGES: "{{ .Values.disableChallenges }}"
  ENABLE_CAPTCHA: "{{ .Values.enableCaptcha }}"
  {{- if .Values.maxBalance }}
  MAX_BALANCE: "{{ .Values.maxBalance }}"
  {{- end }}
  REDIS_URL: "{{ .Values.redis.url }}"
  RPC_URL: "{{ .Values.backendRpcUrl | default .Values.config.network.rpcUrl | required "An rpc url is required." }}"
  MIN_MAV: "{{ .Values.minMav }}"
  MAX_MAV: "{{ .Values.maxMav }}"
  MIN_CHALLENGES: "{{ .Values.minChallenges }}"
  MAX_CHALLENGES: "{{ .Values.maxChallenges }}"
  MAX_CHALLENGES_WITH_CAPTCHA: "{{ .Values.maxChallengesWithCaptcha }}"
  CHALLENGE_SIZE: "{{ .Values.challengeSize }}"
  DIFFICULTY: "{{ .Values.difficulty }}"
  FAUCET_CONTRACT_ADDRESS: "{{ .Values.faucetContractAddress }}"
