apiVersion: v2
name: authenticated-rpc-mavryk-chain
description: A Helm chart for Mavryk RPC authentication for a private chain
type: application
version: 0.0.0
keywords:
  - mavryk
  - blockchain
home: https://github.com/mavryk-network/mavryk-k8s
