{{- range .Values.signers }}
{{- $name := .name }}
{{- range $i, $endpoint := .endpoints }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mavryk-signer-forwarder-config-{{ $name }}-{{ $i }}
data:
  authorized_keys: "{{ $endpoint.ssh_pubkey }} signer"
---
{{- end }}
{{- end }}
