{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
{{- toYaml .Values.prometheusRule.labels | nindent 4 }}
  name: mavryk-remote-signer-rules
spec:
  groups:
  - name: mavryk-remote-signer.rules
    rules:
    - alert: SignerPowerLoss
      annotations:
        description: 'Remote signer "{{`{{ $labels.mavryk_endpoint_name }}`}}" for baker "{{`{{ $labels.mavryk_baker_name }}`}}" has lost power'
        summary: 'Remote signer "{{`{{ $labels.mavryk_endpoint_name }}`}}" for baker "{{`{{ $labels.mavryk_baker_name }}`}}" has lost power'
      expr: power{namespace="{{ .Release.Namespace }}"} != 0
      for: 1m
      labels:
        severity: critical
        alertType: mavryk-remote-signer-alert
    - alert: SignerWiredNetworkLoss
      annotations:
        description: 'Remote signer "{{`{{ $labels.mavryk_endpoint_name }}`}}" for baker "{{`{{ $labels.mavryk_baker_name }}`}}" has lost wired internet connection'
        summary: 'Mavryk remote signer "{{`{{ $labels.mavryk_endpoint_name }}`}}" for baker "{{`{{ $labels.mavryk_baker_name }}`}}" has lost wired internet connection'
      expr: wired_network{namespace="{{ .Release.Namespace }}"} != 0
      for: 1m
      labels:
        severity: critical
        alertType: mavryk-remote-signer-alert
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
{{- toYaml .Values.prometheusRule.labels | nindent 4 }}
  name: mavryk-remote-signer-reachability-rules
spec:
  groups:
  - name: mavryk-remote-signer.rules
    rules:
    - alert: NoRemoteSigner
      annotations:
        description: 'Remote signer "{{`{{ $labels.mavryk_endpoint_name }}`}}" for baker "{{`{{ $labels.mavryk_baker_name }}`}}" is down'
        summary: 'Remote signer "{{`{{ $labels.mavryk_endpoint_name }}`}}" for baker "{{`{{ $labels.mavryk_baker_name }}`}}" is down or unable to sign.'
      expr: unhealthy_signers_total{namespace="{{ .Release.Namespace }}"} != 0
      for: 1m
      labels:
        severity: critical
        alertType: mavryk-remote-signer-alert
---
{{- end }}
