{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mavpay.fullname" . }}-config
  labels:
    {{- include "mavpay.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.hjson: |-
{{ .Values.config.content | indent 4 }}
  {{- if .Values.config.privateKey }}
  payout_wallet_private.key: {{ .Values.config.privateKey | quote }}
  {{- end }}
  {{- if .Values.config.remoteSigner }}
  remote_signer.hjson: |-
{{ .Values.config.remoteSigner | indent 4 }}
  {{- end }}
{{- end }}
