apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mavryk-reward-distributor.fullname" . }}-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- with .Values.storage.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
