apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: pyrometer-volume
  namespace: {{ .Release.Namespace }}
spec:
 storageClassName: {{ .Values.persistence.storageClassName }}
 accessModes:
    - ReadWriteOnce
 resources:
   requests:
     storage: {{ .Values.persistence.storage }}
