---
# Source: mavryk-bridge-signer/templates/signer.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '-mavryk-bridge-signer'
  labels:
    app: '-mavryk-bridge-signer'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: '-mavryk-bridge-signer'
  template:
    metadata:
      labels:
        app: '-mavryk-bridge-signer'
    spec:
      containers:
        - name: mavryk-bridge-signer
          resources:
            requests:
              memory: '128Mi'
              cpu: '50m'
            limits:
              memory: '256Mi'
              cpu: '100m'
          env:
          - name: MAV_SIGNATORY_SK
            valueFrom:
              secretKeyRef:
                name: signer-secret
                key: MAV_SIGNATORY_SK
          - name: ETH_SIGNATORY_SK
            valueFrom:
              secretKeyRef:
                name: signer-secret
                key: ETH_SIGNATORY_SK
          - name: MVKT_ATLASNET_URL
            value: 
          - name: SUBSQUID_EVM_URL
            value: 
          - name: EVM_NODE_URL
            value: 
          - name: EVM_NODE_WS_URL
            value: 
          - name: RPC_NODE_URL
            value: 
          image: '/:'
          imagePullPolicy: 'Always'
